package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA

import logica.CursoLogic;
import logica.EstudianteLogic;




/**
 * CursoEstudiante generated by hbm2java
 */
public class CursoEstudiante  implements java.io.Serializable {


     private int curestId;
     private Estudiante estudiante;
     private Estado estado;
     private Curso curso;

    public CursoEstudiante() {
    }

	
    public CursoEstudiante(int curestId, Estudiante estudiante, Curso curso) {
        this.curestId = curestId;
        this.estudiante = estudiante;
        this.curso = curso;
    }
    public CursoEstudiante(int curestId, Estudiante estudiante, Estado estado, Curso curso) {
       this.curestId = curestId;
       this.estudiante = estudiante;
       this.estado = estado;
       this.curso = curso;
    }
   
    public int getCurestId() {
        return this.curestId;
    }
    
    public void setCurestId(int curestId) {
        this.curestId = curestId;
    }
    public Estudiante getEstudiante() {
        EstudianteLogic el = new EstudianteLogic();
        return el.obtenerUnico(""+this.estudiante.getPerId());
        //return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Curso getCurso() {
        CursoLogic cl = new CursoLogic();
        return cl.buscarUnico(""+this.curso.getCurId());
        //return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }




}


