package Clases;
// Generated 25/07/2013 01:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int usuId;
     private String usuLogin;
     private String usuPassword;
     private Short usuTipo;

    public Usuario() {
    }

	
    public Usuario(int usuId) {
        this.usuId = usuId;
    }
    public Usuario(int usuId, String usuLogin, String usuPassword, Short usuTipo) {
       this.usuId = usuId;
       this.usuLogin = usuLogin;
       this.usuPassword = usuPassword;
       this.usuTipo = usuTipo;
    }
   
    public int getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(int usuId) {
        this.usuId = usuId;
    }
    public String getUsuLogin() {
        return this.usuLogin;
    }
    
    public void setUsuLogin(String usuLogin) {
        this.usuLogin = usuLogin;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public Short getUsuTipo() {
        return this.usuTipo;
    }
    
    public void setUsuTipo(Short usuTipo) {
        this.usuTipo = usuTipo;
    }




}


